const fruits = [
  "Apple",
  "Apricot",
  "Avocado",
  "Banana",
  "Bilberry",
  "Blackberry",
  "Blackcurrant",
  "Blueberry",
  "Boysenberry",
  "Cantaloupe",
  "Currant",
  "Cherry",
  "Cherimoya",
  "Cloudberry",
  "Coconut",
  "Cranberry",
  "Cucumber",
  "Custard apple",
  "Damson",
  "Date",
  "Dragonfruit",
  "Durian",
  "Elderberry",
  "Feijoa",
  "Fig",
  "Goji berry",
  "Gooseberry",
  "Grape",
  "Raisin",
  "Grapefruit",
  "Guava",
  "Honeyberry",
  "Huckleberry",
  "Jabuticaba",
  "Jackfruit",
  "Jambul",
  "Jostaberry",
  "Jujube",
  "Juniper berry",
  "Kiwifruit",
  "Kumquat",
  "Lemon",
  "Lime",
  "Loganberry",
  "Longan",
  "Loquat",
  "Lychee",
  "Mango",
  "Mangosteen",
  "Marionberry",
  "Melon",
  "Cantaloupe",
  "Galia",
  "Honeydew",
  "Watermelon",
  "Miracle fruit",
  "Mulberry",
  "Nectarine",
  "Nance",
  "Olive",
  "Orange",
  "Blood orange",
  "Clementine",
  "Mandarine",
  "Tangerine",
  "Papaya",
  "Passionfruit",
  "Peach",
  "Pear",
  "Persimmon",
  "Plantain",
  "Plum",
  "Pineapple",
  "Pomegranate",
  "Pomelo",
  "Quince",
  "Raspberry",
  "Salmonberry",
  "Rambutan",
  "Redcurrant",
  "Salal berry",
  "Salak",
  "Satsuma",
  "Soursop",
  "Star fruit",
  "Strawberry",
  "Surinam cherry",
  "Tamarillo",
  "Tamarind",
  "Tangelo",
  "Tayberry",
  "Ugli fruit",
  "White currant",
  "White sapote",
  "Yuzu",
  "Acerola",
  "Ackee",
  "African cucumber",
  "American mayapple",
  "American persimmon",
  "Atemoya",
  "Babaco",
  "Bael",
  "Barbados cherry",
  "Barberry",
  "Bignay",
  "Biriba",
  "Bitter melon",
  "Black sapote",
  "Bok choy",
  "Breadfruit",
  "Buddha's hand",
  "Cacao",
  "Calabash",
  "Calamansi",
  "Canistel",
  "Capuli cherry",
  "Cardon",
  "Cempedak",
  "Chempedak",
  "Chayote",
  "Chayote fruit",
  "Chinese date",
  "Chocolate vine",
  "Chokecherry",
  "Chupa-chupa",
  "Clementine",
  "Cocona",
  "Cocoplum",
  "Cocoyam",
  "Coffee cherry",
  "Cornelian cherry",
  "Crowberry",
  "Cupuacu",
  "Davidson's plum",
  "Dead man's fingers",
  "Desert lime",
  "Dodder laurel",
  "Double coconut",
  "Duku",
  "Duku fruit",
  "Duku-langsat",
  "Dwarf banana",
  "Emu apple",
  "Emu berry",
  "False mastic",
  "Finger lime",
  "Forest strawberries",
  "Fox grape",
  "Gac",
  "Gamboge",
  "Genip",
  "Giant granadilla",
  "Giant horned cucumber",
  "Golden apple",
  "Goumi",
  "Grumichama",
  "Guavaberry",
  "Hala fruit",
  "Hawthorn",
  "Hog plum",
  "Horned melon",
  "Indian almond",
  "Indian fig",
  "Indian gooseberry",
  "Indian jujube",
  "Indian prune",
  "Indian sherbet berry",
  "Ivory nut",
  "Jabuticaba fruit",
  "Jamaica cherry",
  "Japanese plum",
  "Japanese raisin tree",
  "Jelly palm",
  "Jelly palm fruit",
  "Jocote",
  "Kei apple",
  "Kepel fruit",
  "Keule",
  "Korlan",
  "Kwai muk",
  "Lablab",
  "Lablab bean",
  "Lakoocha",
  "Langsat",
  "Lapsi",
  "Lardizabala",
  "Lemato",
  "Lucuma",
  "Madrono",
  "Malay apple",
  "Mammee apple",
  "Mamoncillo",
  "Mandarin orange",
  "Mangaba",
  "Mangosteen",
  "Manoao",
  "Marang",
  "Marang fruit",
  "Marula",
  "Masau",
  "Maypop",
  "Medlar",
  "Melinjo",
  "Midyim",
  "Mimosa",
  "Monkey apple",
  "Monkey-bread tree",
  "Monstera",
  "Monstera deliciosa",
  "Monstera fruit",
  "Mountain papaya",
  "Mulberry",
  "Muricara",
  "Nageia nagi",
  "Nam nam",
  "Nance fruit",
  "Natal plum",
  "Natto bean",
  "Nere",
  "Nispero",
  "Nutmeg",
  "Ogeechee tupelo",
  "Ohelo",
  "Oil palm",
  "Okari nut",
  "Olosapo",
  "Oregon grape",
  "Otaheite apple",
  "Papeda",
  "Peach palm",
  "Peach-palm fruit",
  "Peanut butter fruit",
  "Pegu pear",
  "Pejibaye",
  "Pendula",
  "Pequi",
  "Peruvian apple",
  "Pigeon pea",
  "Pigeon plum",
  "Pitanga",
  "Pitangatuba",
  "Pitangueira",
  "Pitaya",
  "Pitomba",
  "Pitomba de Galinha",
  "Plantain",
  "Poha berry",
  "Pomegranate",
  "Ponderosa lemon",
  "Prickly pear",
  "Pummelo",
  "Quandong",
  "Rambutan",
  "Rangpur",
  "Rata",
  "Red banana",
  "Red currant",
  "Red huckleberry",
  "Rhubarb",
  "Riberry",
  "Rimu",
  "Rose apple",
  "Rowan",
  "Salak",
  "Sapotillo",
  "Sapotille",
  "Sea buckthorn",
  "Sennaberry",
  "Serviceberry",
  "Sloe",
  "Snowberry",
  "Soncoya",
  "Sorrel",
  "Spanish lime",
  "Spanish tamarind",
  "Sour cherry",
  "Sour fig",
  "Sour orange",
  "Southern crabapple",
  "Soursop",
  "Spiny monkey orange",
  "Spondias",
  "Star apple",
  "Strawberry guava",
  "Sugar apple",
  "Surinam cherry",
  "Sweet granadilla",
  "Sweet lemon",
  "Sweet lime",
  "Sweet orange",
  "Tamarind",
  "Tangerine",
  "Taperiba",
  "Tart cherry",
  "Tatjana's cherry",
  "Tayberry",
  "Texas persimmon",
  "Thimbleberry",
  "Tigernut",
  "Tree tomato",
  "Trifoliate orange",
  "Trochetia",
  "Tucuma",
  "Ugni",
  "Ume",
  "Uva",
  "Velvet apple",
  "Velvet tamarind",
  "Victoria plum",
  "Voavanga",
  "Water apple",
  "Water lemon",
  "Wax apple",
  "White currant",
  "White mulberry",
  "Wild lime",
  "Wild plum",
  "Wild strawberry",
  "Wineberry",
  "Winter melon",
  "Wolfberry",
  "Wood apple",
  "Woolly tea-tree",
  "Yangmei",
  "Yellow granadilla",
  "Yellow mombin",
  "Yellow sapote",
  "Yew berry",
  "Ylang-ylang",
  "Zhe fruit",
  "Zwetschge",
];


module.exports = { fruits };
